# Generated by Django 3.2 on 2021-04-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='folder_name',
        ),
    ]
