# Generated by Django 3.2 on 2021-04-22 09:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('bookmarkApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='name',
        ),
        migrations.AddField(
            model_name='folder',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
